### ISSUE TITLE
I offer myself as maintainer for the project

### ISSUE THREAD

**Issue by Zeioth** [dln/wofi-emoji#13]
I realize you don't have much time to pay attention to opened issues and the AUR repository, so I'd like to step as a maintainer. In the meantime I've applyed the PRs to https://github.com/Zeioth/wofi-emoji and I will be maintaining it there.

**Comment by gilbsgilbs** [comment]
As @dln seems to have disconnected, maybe you could rename your fork (something like "wofimoji"), create an AUR package for it and restart from there? If necessary, I can maintain the AUR package myself, and even automate updates from Github releases (instead of having a `-git` package).

**Comment by dln** [comment]
Sorry for the late response here, but yeah that sounds great! I'll update the README with a link and archive the repo for future visitors. Thanks for offering, @Zeioth! :rocket:

**Comment by Zeioth** [comment]
Thank you for making it in the first place! I'm Glad if I can help.
