### ISSUE TITLE
Use wl-copy when wtype doesn't work for the compositor used

### ISSUE THREAD

**Issue by PotHix** [dln/wofi-emoji#8]
It seems wtype is not yet supported on all compositor. In Gnome, I get the following error:

```
/tmp ❯ echo 'test' | wtype -
Compositor does not support the virtual keyboard protocol
/tmp ❯ echo $?
1
```

It would be nice to be able to use `wl-copy` (as it did before) in case `wtype` is not supported.

**Comment by PotHix** [comment]
Meanwhile, I just changed it to the following and it's working for me:

```
#!/bin/bash
wtype 0
if [ $? -eq 0 ]
then
        sed '1,/^### DATA ###$/d' $0 | wofi --show dmenu -i | cut -d ' ' -f 1 | tr -d '\n' | wtype -
else
        sed '1,/^### DATA ###$/d' $0 | wofi --show dmenu -i | cut -d ' ' -f 1 | tr -d '\n' | wl-copy
fi
exit
### DATA ###
```

**Comment by gbatiz** [comment]
Confirmed indeed, this affects Gnome 42.1 on Arch, and the manual override works.
@PotHix Thanks for the solution! Would you have time to make a pull request?

**Comment by PotHix** [comment]
@gbatiz it's done. I was waiting for someone else to come up with a better implementation, but just suggested the one above while I don't have enough time to provide something better.

Let's wait for @dln to merge this. :)

**Comment by gbatiz** [comment]
Nice move! Indeed hope he merges it soon!

**Comment by PotHix** [comment]
#9 was merged. We can close this. :)
